name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    uses: reallifedeveloper/github-workflows/.github/workflows/release.yaml@main
